// location.js
export const location = [
    {   
        name:"Alaska",
        value:"AK",
        short_name:"AK"
    },
    {   
        name:"Alabama",
        value:"AL",
        short_name:"AL"
    },
    {   
        name:"Arkansas",
        value:"AR",
        short_name:"AR"
    },
    {   
        name:"Arizona",
        value:"AZ",
        short_name:"AZ"
    },
    {   
        name:"California",
        value:"CA",
        short_name:"CA"
    },
    {   
        name:"Colorado",
        value:"CO",
        short_name:"CO"
    },
    {   
        name:"Connecticut",
        value:"CT",
        short_name:"CT"
    },
    {   
        name:"Delaware",
        value:"DE",
        short_name:"DE"
    },
    {   
        name:"Florida",
        value:"FL",
        short_name:"FL"
    },
    {   
        name:"Georgia",
        value:"GA",
        short_name:"GA"
    },
    {   
        name:"Hawaii",
        value:"HI",
        short_name:"HI"
    },
    {   
        name:"Iowa",
        value:"IA",
        short_name:"IA"
    },
    {   
        name:"Idaho",
        value:"ID",
        short_name:"ID"
    },
    {   
        name:"Illinois",
        value:"IL",
        short_name:"IL"
    },
    {   
        name:"Indiana",
        value:"IN",
        short_name:"IN"
    },
    {   
        name:"Kansas",
        value:"KS",
        short_name:"KS"
    },
    {   
        name:"Kentucky",
        value:"KY",
        short_name:"KY"
    },
    {   
        name:"Louisiana",
        value:"LA",
        short_name:"LA"
    },
    {   
        name:"Massachusetts",
        value:"MA",
        short_name:"MA"
    },
    {   
        name:"Maryland",
        value:"MD",
        short_name:"MD"
    },
    {   
        name:"Maine",
        value:"ME",
        short_name:"ME"
    },
    {   
        name:"Michigan",
        value:"MI",
        short_name:"MI"
    },
    {   
        name:"Minnesota",
        value:"MN",
        short_name:"MN"
    },
    {   
        name:"Missouri",
        value:"MO",
        short_name:"MO"
    },
    {   
        name:"Mississippi",
        value:"MS",
        short_name:"MS"
    },
    {   
        name:"Montana",
        value:"MT",
        short_name:"MT"
    },
    {   
        name:"North Carolina",
        value:"NC",
        short_name:"NC"
    },
    {   
        name:"North Dakota",
        value:"ND",
        short_name:"ND"
    },
    {   

        name:"Nebraska",
        value:"NE",
        short_name:"NE"
    },
    {   
        name:"New Hampshire",
        value:"NH",
        short_name:"NH"
    },
    {   
        name:"New Jersey",
        value:"NJ",
        short_name:"NJ"
    },
    {   
        name:"New Mexico",
        value:"NM",
        short_name:"NM"
    },
    {   
        name:"Nevada",
        value:"NV",
        short_name:"NV"
    },
    {   
        name:"New York",
        value:"NY",
        short_name:"NY"
    },
    {   
        name:"Ohio",
        value:"OH",
        short_name:"OH"
    },
    {   
        name:"Oklahoma",
        value:"OK",
        short_name:"OK"
    },
    {   
        name:"Oregon",
        value:"OR",
        short_name:"OR"
    },
    {   
        name:"Pennsylvania",
        value:"PA",
        short_name:"PA"
    },
    {   
        name:"Rhode Island",
        value:"RI",
        short_name:"RI"
    },
    {   
        name:"South Carolina",
        value:"SC",
        short_name:"SC"
    },
    {   
        name:"South Dakota",
        value:"SD",
        short_name:"SD"
    },
    {   
        name:"Tennessee",
        value:"TN",
        short_name:"TN"
    },
    {   
        name:"Texas",
        value:"TX",
        short_name:"TX"
    },
    {   
        name:"Utah",
        value:"UT",
        short_name:"UT"
    },
    {   
        name:"Virginia",
        value:"VA",
        short_name:"VA"
    },
    {   
        name:"Vermont",
        value:"VT",
        short_name:"VT"
    },
    {   
        name:"Washington",
        value:"WA",
        short_name:"WA"
    },
    {   
        name:"Wisconsin",
        value:"WI",
        short_name:"WI"
    },
    {   
        name:"West Virginia",
        value:"WV",
        short_name:"WV"
    },
    {   
        name:"Wyoming",
        value:"WY",
        short_name:"WY"
    },
]